add: junit report

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -45,5 +45,12 @@ jobs:
         run: npm run build
       - name: Run tests
         run: npm run test
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+            name: JEST Tests            # Name of the check run which will be created
+            path: junit.xml    # Path to test results
+            reporter: jest-junit        # Format of test result
       - name: Run linting
         run: npm run lint
